#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTServo,  none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Motor,  mtr_S1_C1_1,     motorD,        tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C1_2,     motorE,        tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C2_1,     motorF,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_2,     motorG,        tmotorTetrix, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "JoystickDriver.c"

task move()
{
	static int speed = 50, m_speed = -50, slow_speed = 20, slow_m_speed = -20;

	while (joy1Btn(10) != 1)
  {}


	while (true)
	{
		while (joy1Btn (7)) /* turn left */
		{
			motor[motorE] = speed;
			motor[motorD] = speed;
			motor[motorF] = speed;
			motor[motorG] = speed;
		}

		while (joy1Btn (8)) /* turn right*/
		{
			motor[motorE] = m_speed;
			motor[motorD] = m_speed;
			motor[motorF] = m_speed;
			motor[motorG] = m_speed;
		}

		while (joy1Btn (4)) /* move forward*/
		{
			motor[motorE] = m_speed;
			motor[motorD] = m_speed;
			motor[motorF] = speed;
			motor[motorG] = speed;
		}

		while (joy1Btn (2)) /* move backward */
		{
			motor[motorE] = speed;
			motor[motorD] = speed;
			motor[motorF] = m_speed;
			motor[motorG] = m_speed;
		}

		while (joy1Btn (1)) /* move left */
		{
			motor[motorE] = speed;
			motor[motorD] = m_speed;
			motor[motorF] = m_speed;
			motor[motorG] = speed;
		}

		while (joy1Btn (3)) /* move right */
		{
			motor[motorE] = m_speed;
			motor[motorD] = speed;
			motor[motorF] = speed;
			motor[motorG] = m_speed;
		}

		while (joystick.joy1_TopHat == 0) /* slow move forward */
		{
			motor[motorE] = slow_m_speed;
			motor[motorD] = slow_m_speed;
			motor[motorF] = slow_speed;
			motor[motorG] = slow_speed;
		}

		while (joystick.joy1_TopHat == 4) /* slow move backward */
		{
			motor[motorE] = slow_speed;
			motor[motorD] = slow_speed;
			motor[motorF] = slow_m_speed;
			motor[motorG] = slow_m_speed;
		}

		while (joystick.joy1_TopHat == 6) /* slow move left */
		{
			motor[motorE] = slow_speed;
			motor[motorD] = slow_m_speed;
			motor[motorF] = slow_m_speed;
			motor[motorG] = slow_speed;
		}

		while (joystick.joy1_TopHat == 2) /* slow move right */
		{
			motor[motorE] = slow_m_speed;
			motor[motorD] = slow_speed;
			motor[motorF] = slow_speed;
			motor[motorG] = slow_m_speed;
		}

		while (joy1Btn (6)) /* slow turn right*/
		{
			motor[motorE] = slow_m_speed;
			motor[motorD] = slow_m_speed;
			motor[motorF] = slow_m_speed;
			motor[motorG] = slow_m_speed;
		}

		while (joy1Btn (5)) /* slow turn left */
		{
			getJoystickSettings(joystick);

			motor[motorE] = slow_speed;
			motor[motorD] = slow_speed;
			motor[motorF] = slow_speed;
			motor[motorG] = slow_speed;
		}

		while (joy1Btn (9)) /* turn servo - flag */
		{
			servo[servo1] = 0; /* 0 - Full Power/ Speed Reverse; 127 - Stop; 256 - Full Power/ Speed Forward */
		}

		motor[motorE] = 0;
		motor[motorD] = 0;
		motor[motorF] = 0;
		motor[motorG] = 0;
		servo[servo1] = 127;
	}
}

task capture ()
{
	/* .... */
}

task main ()
{
	StartTask(move);
	StartTask(capture);

	while (true)
		getJoystickSettings(joystick);
}
