#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTMotor,  HTServo)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Motor,  mtr_S1_C1_1,     motorD,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     motorE,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_1,     motorF,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_2,     motorG,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_1,     motorH,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_2,     motorI,        tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S1_C4_1,    servo1,               tServoNone)
#pragma config(Servo,  srvo_S1_C4_2,    servo2,               tServoNone)
#pragma config(Servo,  srvo_S1_C4_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S1_C4_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S1_C4_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C4_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#define Forward_L motor[motorG]
#define Forward_R motor[motorH]
#define Backward_L motor[motorF]
#define Backward_R motor[motorI]
#define Flag_Raise servo[servo1]

#include "JoystickDriver.c"

task move()
{
	static int speed = 50, m_speed = -50, slow_speed = 20, slow_m_speed = -20;

	Forward_L = 0;
	Backward_L = 0;
	Forward_R = 0;
	Backward_R = 0;

	Flag_Raise = 127;

	while (joy1Btn(10) != 1)
	getJoystickSettings(joystick);


	while(true)
	{
		if (joy1Btn (7))
		{
			while (joy1Btn (7)) /* turn left */
			{
	    	Forward_L = speed;
	    	Backward_L = speed;
	    	Forward_R = speed;
	    	Backward_R = speed;
			}

		  while (Forward_L >= 0)
	 	 	{
	  		Forward_L -= 1;
	  		Backward_L -= 1;
	  		Forward_R -= 1;
	  		Backward_R -= 1;
	  	}
	  	if (Forward_L != 0 || Forward_R != 0 || Backward_L != 0 || Backward_R != 0)
	  	{
	  		Forward_L = 0;
	  		Backward_L = 0;
	  		Forward_R = 0;
	  		Backward_R = 0;
	  	}
	  }

		if (joy1Btn (8))
		{
			while (joy1Btn (8)) /* turn right*/
			{
	    	Forward_L = m_speed;
	    	Backward_L = m_speed;
	    	Forward_R = m_speed;
	    	Backward_R = m_speed;
			}

      while (Forward_L <= 0)
      {
      	Forward_L += 1;
	  		Backward_L += 1;
	  		Forward_R += 1;
	  		Backward_R += 1;
	  	}
	  	if (Forward_L != 0 || Forward_R != 0 || Backward_L != 0 || Backward_R != 0)
	  	{
	  		Forward_L = 0;
	  		Backward_L = 0;
	  		Forward_R = 0;
	  		Backward_R = 0;
	  	}
	  }

	  if (joy1Btn (4))
	  {
			while (joy1Btn (4)) /* move forward*/
			{
	    	Forward_L = m_speed;
	    	Backward_L = m_speed;
	    	Forward_R = speed;
	    	Backward_R = speed;
			}

			while (Forward_L <= 0)
			{
				Forward_L += 1;
	  		Backward_L += 1;
	  		Forward_R -= 1;
	  		Backward_R -= 1;
	  	}
	  	if (Forward_L != 0 || Forward_R != 0 || Backward_L != 0 || Backward_R != 0)
	  	{
	  		Forward_L = 0;
	  		Backward_L = 0;
	  		Forward_R = 0;
	  		Backward_R = 0;
	  	}
	  }

	  if (joy1Btn (2))
	  {
			while (joy1Btn (2)) /* move backward */
			{
	    	Forward_L = speed;
	    	Backward_L = speed;
	    	Forward_R = m_speed;
	    	Backward_R = m_speed;
    	}

    	while (Forward_L >= 0)
    	{
    		Forward_L -= 1;
	  		Backward_L -= 1;
	  		Forward_R += 1;
	  		Backward_R += 1;
	  	}
	  	if (Forward_L != 0 || Forward_R != 0 || Backward_L != 0 || Backward_R != 0)
	  	{
	  		Forward_L = 0;
	  		Backward_L = 0;
	  		Forward_R = 0;
	  		Backward_R = 0;
	  	}
	  }

	  if (joy1Btn (1))
	  {
			while (joy1Btn (1)) /* move left */
			{
	   	  Forward_L = speed;
	    	Backward_L = m_speed;
	    	Forward_R = m_speed;
	    	Backward_R = speed;
			}

			while (Forward_L >= 0)
			{
				Forward_L -= 1;
	  		Backward_L += 1;
	  		Forward_R += 1;
	  		Backward_R -= 1;
	  	}
	  	if (Forward_L != 0 || Forward_R != 0 || Backward_L != 0 || Backward_R != 0)
	  	{
	  		Forward_L = 0;
	  		Backward_L = 0;
	  		Forward_R = 0;
	  		Backward_R = 0;
	  	}
	  }

	  if (joy1Btn (3))
	  {
	  	while (joy1Btn (3)) /* move right */
			{
				Forward_L = m_speed;
	    	Backward_L = speed;
	    	Forward_R = speed;
	    	Backward_R = m_speed;
			}

			while (Forward_L <= 0)
			{
	  		Forward_L += 1;
	  		Backward_L -= 1;
	  		Forward_R -= 1;
	  		Backward_R += 1;
	  	}
	  	if (Forward_L != 0 || Forward_R != 0 || Backward_L != 0 || Backward_R != 0)
	  	{
	  		Forward_L = 0;
	  		Backward_L = 0;
	  		Forward_R = 0;
	  		Backward_R = 0;
	  	}
	  }

	  if (joystick.joy1_TopHat == 0)
	  {
			while (joystick.joy1_TopHat == 0) /* slow move forward */
			{
	    	Forward_L = slow_m_speed;
	    	Backward_L = slow_m_speed;
	    	Forward_R = slow_speed;
	    	Backward_R = slow_speed;
			}

			while (Forward_L <= 0)
			{
				Forward_L += 1;
	  		Backward_L += 1;
	  		Forward_R -= 1;
	  		Backward_R -= 1;
	  	}
	  	if (Forward_L != 0 || Forward_R != 0 || Backward_L != 0 || Backward_R != 0)
	  	{
	  		Forward_L = 0;
	  		Backward_L = 0;
	  		Forward_R = 0;
	  		Backward_R = 0;
	  	}
	  }

	  if (joystick.joy1_TopHat == 4)
	  {
	  	while (joystick.joy1_TopHat == 4) /* slow move backward */
			{
	    	Forward_L = slow_speed;
	    	Backward_L = slow_speed;
	    	Forward_R = slow_m_speed;
	    	Backward_R = slow_m_speed;
			}

			while (Forward_L >= 0)
			{
				Forward_L -= 1;
	  		Backward_L -= 1;
	  		Forward_R += 1;
	  		Backward_R += 1;
	  	}
	  	if (Forward_L != 0 || Forward_R != 0 || Backward_L != 0 || Backward_R != 0)
	  	{
	  		Forward_L = 0;
	  		Backward_L = 0;
	  		Forward_R = 0;
	  		Backward_R = 0;
	  	}
	  }

	  if (joystick.joy1_TopHat == 6)
	  {
			while (joystick.joy1_TopHat == 6) /* slow move left */
			{
      	Forward_L = slow_speed;
	    	Backward_L = slow_m_speed;
	    	Forward_R = slow_m_speed;
	    	Backward_R = slow_speed;
			}

			while (Forward_L >= 0)
			{
				Forward_L -= 1;
	  		Backward_L += 1;
	  		Forward_R += 1;
	  		Backward_R -= 1;
	  	}
	  	if (Forward_L != 0 || Forward_R != 0 || Backward_L != 0 || Backward_R != 0)
	  	{
	  		Forward_L = 0;
	  		Backward_L = 0;
	  		Forward_R = 0;
	  		Backward_R = 0;
	  	}
	  }

	  if (joystick.joy1_TopHat == 2)
	  {
			while (joystick.joy1_TopHat == 2) /* slow move right */
			{
      	Forward_L = slow_m_speed;
	  		Backward_L = slow_speed;
	    	Forward_R = slow_speed;
	    	Backward_R = slow_m_speed;
			}

			while (Forward_L <= 0)
			{
				Forward_L += 1;
	  		Backward_L -= 1;
	  		Forward_R -= 1;
	  		Backward_R += 1;
	  	}
	  	if (Forward_L != 0 || Forward_R != 0 || Backward_L != 0 || Backward_R != 0)
	  	{
	  		Forward_L = 0;
	  		Backward_L = 0;
	  		Forward_R = 0;
	  		Backward_R = 0;
	  	}
	  }

	  if (joy1Btn (6))
	  {
			while (joy1Btn (6)) /* slow turn right*/
			{
      	Forward_L = slow_m_speed;
	    	Backward_L = slow_m_speed;
	    	Forward_R = slow_m_speed;
	    	Backward_R = slow_m_speed;
			}

			while (Forward_L <= 0)
			{
				Forward_L += 1;
	  		Backward_L += 1;
	  		Forward_R += 1;
	  		Backward_R += 1;
	  	}
	  	if (Forward_L != 0 || Forward_R != 0 || Backward_L != 0 || Backward_R != 0)
	  	{
	  		Forward_L = 0;
	  		Backward_L = 0;
	  		Forward_R = 0;
	  		Backward_R = 0;
	  	}
	  }

	  if (joy1Btn (5))
	  {
			while (joy1Btn (5)) /* slow turn left */
			{
      	Forward_L = slow_speed;
	    	Backward_L = slow_speed;
	    	Forward_R = slow_speed;
	    	Backward_R = slow_speed;
			}

			while (Forward_L >= 0)
			{
				Forward_L -= 1;
	  		Backward_L -= 1;
	  		Forward_R -= 1;
	  		Backward_R -= 1;
	  	}
	  	if (Forward_L != 0 || Forward_R != 0 || Backward_L != 0 || Backward_R != 0)
	  	{
	  		Forward_L = 0;
	  		Backward_L = 0;
	  		Forward_R = 0;
	  		Backward_R = 0;
	  	}
	  }

		while (joy1Btn (9))
		{
			Flag_Raise = 0; /* 0 - Full Power/ Speed Reverse; 127 - Stop; 256 - Full Power/ Speed Forward */
		}

	Forward_L = 0;
	Backward_L = 0;
	Forward_R = 0;
	Backward_R = 0;
	Flag_Raise = 127;
	}
}

task capture ()
{
}

task main ()
{
	StartTask(move);
	StartTask(capture);

	while (true)
		getJoystickSettings(joystick);
}
